export const productList = [
  {
    id: 1,
    name: "Product 1",
    price: 19.99,
    category: "Electronics",
    description: "A high-quality electronic product.",
  },
  {
    id: 2,
    name: "Product 2",
    price: 29.99,
    category: "Clothing",
    description: "A stylish piece of clothing.",
  },
  {
    id: 3,
    name: "Product 3",
    price: 9.99,
    category: "Kitchen",
    description: "A useful kitchen gadget.",
  },
  {
    id: 4,
    name: "Product 4",
    price: 49.99,
    category: "Electronics",
    description: "A cutting-edge electronic device.",
  },
  {
    id: 5,
    name: "Product 5",
    price: 14.99,
    category: "Books",
    description: "A best-selling book.",
  },
  {
    id: 6,
    name: "Product 6",
    price: 39.99,
    category: "Clothing",
    description: "Fashionable clothing item.",
  },
  {
    id: 7,
    name: "Product 7",
    price: 7.99,
    category: "Home Decor",
    description: "Beautiful home decor accessory.",
  },
  {
    id: 8,
    name: "Product 8",
    price: 59.99,
    category: "Electronics",
    description: "An advanced electronic gadget.",
  },
  {
    id: 9,
    name: "Product 9",
    price: 24.99,
    category: "Beauty",
    description: "Premium beauty product.",
  },
  {
    id: 10,
    name: "Product 10",
    price: 12.99,
    category: "Toys",
    description: "Fun and interactive toy.",
  },
];
